// Generated by binpac_quickstart

#ifndef ANALYZER_PROTOCOL_OWAMP_OWAMP_H
#define ANALYZER_PROTOCOL_OWAMP_OWAMP_H

#include "events.bif.h"


#include "zeek/analyzer/protocol/tcp/TCP.h"

#include "owamp_pac.h"

namespace zeek::analyzer { namespace OWAMP {

class OWAMP_Analyzer

: public tcp::TCP_ApplicationAnalyzer {

public:
	OWAMP_Analyzer(Connection* conn);
	virtual ~OWAMP_Analyzer();

	// Overriden from Analyzer.
	virtual void Done();

	virtual void DeliverStream(int len, const u_char* data, bool orig);
	virtual void Undelivered(uint64_t seq, int len, bool orig);

	// Overriden from tcp::TCP_ApplicationAnalyzer.
	virtual void EndpointEOF(bool is_orig);


	static analyzer::Analyzer* InstantiateAnalyzer(Connection* conn)
		{ return new OWAMP_Analyzer(conn); }

protected:
	binpac::OWAMP::OWAMP_Conn* interp;

	bool had_gap;

};

} } // namespace analyzer::*

#endif
