// Generated by binpac_quickstart

#include "OWAMP.h"

#include "analyzer/protocol/tcp/TCP_Reassembler.h"

#include "Reporter.h"

#include "events.bif.h"

using namespace analyzer::OWAMP;

OWAMP_Analyzer::OWAMP_Analyzer(Connection* c)

: tcp::TCP_ApplicationAnalyzer("OWAMP", c)

	{
	interp = new binpac::OWAMP::OWAMP_Conn(this);

	had_gap = false;
	
	}

OWAMP_Analyzer::~OWAMP_Analyzer()
	{
	delete interp;
	}

void OWAMP_Analyzer::Done()
	{
	
	tcp::TCP_ApplicationAnalyzer::Done();

	interp->FlowEOF(true);
	interp->FlowEOF(false);
	
	}

void OWAMP_Analyzer::EndpointEOF(bool is_orig)
	{
	tcp::TCP_ApplicationAnalyzer::EndpointEOF(is_orig);
	interp->FlowEOF(is_orig);
	}

void OWAMP_Analyzer::DeliverStream(int len, const u_char* data, bool orig)
	{
	tcp::TCP_ApplicationAnalyzer::DeliverStream(len, data, orig);

	assert(TCP());
	if ( TCP()->IsPartial() )
		return;

	if ( had_gap )
		// If only one side had a content gap, we could still try to
		// deliver data to the other side if the script layer can handle this.
		return;

	if (interp->get_done()){
		// stop analyzing
		return;
		// the return; itself should be enough to stop the analyzer
		// OWAMP_Analyzer::Done();
	}

	try
		{
		interp->NewData(orig, data, data + len);
		}
	catch ( const binpac::Exception& e )
		{
		ProtocolViolation(fmt("Binpac exception: %s", e.c_msg()));
		}
	}

void OWAMP_Analyzer::Undelivered(uint64_t seq, int len, bool orig)
	{
	tcp::TCP_ApplicationAnalyzer::Undelivered(seq, len, orig);
	had_gap = true;
	interp->NewGap(orig, len);
	}
