// Generated by binpac_quickstart

#include "zeek/analyzer/Component.h"
#include "Plugin.h"

#include "OWAMP.h"

namespace zeek::plugin::PerfSONAR_OWAMP { Plugin plugin;}

using namespace zeek::plugin::PerfSONAR_OWAMP;

zeek::plugin::Configuration Plugin::Configure()
		{
		AddComponent(new zeek::analyzer::Component("OWAMP",
		             zeek::analyzer::OWAMP::OWAMP_Analyzer::InstantiateAnalyzer));

		zeek::plugin::Configuration config;
		config.name = "PerfSONAR::OWAMP";
		config.description = "One-Way Active Measurement Protocol analyzer";
		config.version.major = 0;
		config.version.minor = 1;

		return config;
		}